services:
  - type: cron
    name: deep-trends-scheduler
    env: node
    schedule: "*/5 * * * *"  # Run every 5 minutes
    buildCommand: npm install
    startCommand: node src/scripts/runScheduler.ts
    envVars:
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        sync: false
      - key: PERPLEXITY_API_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
    autoDeploy: true 